<?php

/**
 * @file
 * Contains presto_contact.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\node\Entity\Node;

/**
 * Implements hook_help().
 */
function presto_contact_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the presto_contact module.
    case 'help.page.presto_contact':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Configuration for contact page.') . '</p>';
      return $output;

    default:
  }
}


/**
 * Implements hook_install().
 */
function presto_contact_install() {
  // Create node contact, then we can configure contactblock to be displayed
  // in the page.
  $node = Node::create(['type' => 'page']);
  $node->set('title', 'Contact us');
  $body = array(
    'value' => 'Don\'t hesitate to contact us.',
    'format' => 'basic_html',
  );
  $node->set('body', $body);
  $node->set('path', ['alias' => '/contact']);
  $node->save();
}
