<?php

/**
 * @file
 * The Presto Components module file.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements theme_hook().
 */
function presto_components_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__component_divider' => [
      'template' => 'paragraph--component-divider',
      'base hook' => 'paragraph',
    ],
    'paragraph__component_image' => [
      'template' => 'paragraph--component-image',
      'base hook' => 'paragraph',
    ],
    'paragraph__component_promo_bar' => [
      'template' => 'paragraph--component-promo-bar',
      'base hook' => 'paragraph',
    ],
    'paragraph__component_icon_box' => [
      'template' => 'paragraph--component-icon-box',
      'base hook' => 'paragraph',
    ],
    'paragraph__component_icon_box_list' => [
      'template' => 'paragraph--component-icon-box-list',
      'base hook' => 'paragraph',
    ],
  ];
}

/**
 * Implements theme_suggestions_paragraph_alter().
 */
function presto_components_theme_suggestions_paragraph_alter(array &$suggestions, array $variables, $hook) {
  /** @var \Drupal\paragraphs\Entity\Paragraph $paragraph */
  $paragraph = $variables['elements']['#paragraph'];
  $type = $paragraph->getType();
  $suggestions[] = "paragraph__{$type}";
}

/**
 * Implements hook_form_alter().
 */
function presto_components_form_alter(
  &$form,
  FormStateInterface $form_state,
  $form_id
) {
  // Attached some JS to manage the conditional display for IconBox.
  if (isset($form['field_body_paragraphs'])) {
    $form['#attached']['library'][] = 'presto_components/iconbox_conditional_display';
  }
}
